"""initial

Revision ID: 5a28103aeac7
Revises: f8d6ab9a8133
Create Date: 2026-05-22 19:48:24.958318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a28103aeac7'
down_revision: Union[str, Sequence[str], None] = 'f8d6ab9a8133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electricity_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_off', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('water_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_off', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_records')
    op.drop_table('electricity_records')
    # ### end Alembic commands ###
